import Head from "next/head";
import Image from "next/image";
import { useFormik } from "formik";
import * as Yup from "yup";
import { useRouter } from "next/router";
import { motion } from "framer-motion";

export default function Home() {
  //Router
  const router = useRouter();

  //Formik logics

  const formik = useFormik({
    initialValues: {
      name: "",
      email: "",
      country: "PNG",
      terms: "",
    },
    //Validate Form
    validationSchema: Yup.object({
      name: Yup.string()
        .max(20, "Name must be 20characters or less.")
        .required("Name is required"),
      email: Yup.string()
        .email("Invalid email address")
        .required("Email is required"),
      terms: Yup.array().required("Terms of service must be checked!"),
    }),
    //Submit form
    onSubmit: (values) => {
      console.log(values);
      router.push({ pathname: "/success", query: values });
    },
  });

  console.log(formik.errors);

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      className="bg-teal-500"
    >
      <Head>
        <title>Forms</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-screen flex items-center justify-center">
        <form
          onSubmit={formik.handleSubmit}
          className="bg-white flex rounded-lg w-1/2"
        >
          <div className="flex-1 text-gray-700 p-20">
            <h1 className="text-3xl pb-2">Lets get started 👏</h1>
            <p className="text-lg text-gray-500">
              Lorem ipsum dolor sit amet, consectetur adipisicing elit.
            </p>
            <div className="mt-6">
              {/* //input field */}
              <div className="pb-4">
                <label
                  className={`block text-sm pb-2 ${
                    formik.touched.name && formik.errors.name
                      ? "text-red-400"
                      : ""
                  }`}
                  htmlFor="name"
                >
                  {formik.touched.name && formik.errors.name
                    ? formik.errors.name
                    : "Name"}
                </label>
                <input
                  className="border-2 border-gray-500 p-2 rounded-md w-1/2 focus:border-teal-500 focus:ring-teal-400"
                  type="text"
                  name="name"
                  value={formik.values.name}
                  onChange={formik.handleChange}
                  onBlur={formik.handleBlur}
                  placeholder="Enter your name"
                />
              </div>
              {/* Email input field */}
              <div className="pb-4">
                <label
                  className={`block text-sm pb-2 ${
                    formik.touched.email && formik.errors.email
                      ? "text-red-400"
                      : ""
                  }`}
                  htmlFor="email"
                >
                  {formik.touched.email && formik.errors.email
                    ? formik.errors.email
                    : "Email"}
                </label>
                <input
                  className="border-2 border-gray-500 p-2 rounded-md w-1/2 focus:border-teal-500 focus:ring-teal-500"
                  type="email"
                  name="email"
                  value={formik.values.email}
                  onChange={formik.handleChange}
                  onBlur={formik.handleBlur}
                  placeholder="Enter your email"
                />
              </div>
              {/* Country input field */}
              <div className="pb-4">
                <label className="block text-sm pb-2" htmlFor="country">
                  Country
                </label>
                <select
                  name="country"
                  value={formik.values.country}
                  onChange={formik.handleChange}
                  className="border-2 border-gray-500 p-2 rounded-md w-1/2 focus:border-teal-500 focus:ring-teal-500"
                >
                  <option>PNG</option>
                  <option>Australia</option>
                  <option>New Zealand</option>
                  <option>Fiji</option>
                </select>
              </div>

              {/* Terms of service */}
              <div className="pb-4">
                <label
                  className={`block text-sm pb-2 ${
                    formik.touched.terms && formik.errors.terms
                      ? "text-red-400"
                      : ""
                  }`}
                  htmlFor="terms"
                >
                  {formik.touched.terms && formik.errors.terms
                    ? formik.errors.terms
                    : "Terms of service"}
                </label>
                <div className="flex items-center gap-2">
                  <input
                    type="checkbox"
                    name="terms"
                    value="checked"
                    onChange={formik.handleChange}
                    className="h-5 w-5 text-teal-500 border-2 focus:border-teal-500 focus:ring-teal-500"
                  />
                  <p className="text-sm text-gray-500">
                    I agree to the Terms and Serivce that my data will be taken
                    and sold.
                  </p>
                </div>
              </div>
              <button
                type="submit"
                className="bg-teal-500 text-sm text-white py-3 mt-6 rounded-lg w-full"
              >
                Start learning today!
              </button>
            </div>
          </div>
          <div className="flex-1 relative">
            <Image
              src="https://images.pexels.com/photos/1237119/pexels-photo-1237119.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
              alt="form-image"
              fill
              priority
              className="object-cover rounded-lg"
            />
          </div>
        </form>
      </main>
    </motion.div>
  );
}
